name = "hugo-theme-georepublic"
license = "Apache-2.0"
licenselink = "./LICENSE"
description = "Georepublic's basic Hugo theme"
homepage = "https://github.com/Georepublic/hugo-theme-georepublic"
tags = []
features = []
min_version = "0.83.0"

[author]
  name = "Georepublic"
  homepage = "https://georepublic.info"
